### ISSUE TITLE
Hi. Such a great addon, use it constantly. The issue I'm having is the absence of the mini map button. All of the other aspects of the addon work as intended but since the release of 9.1.5 the button is missing. I run a lot of mods but disabiling all but Altreps still results in the minimap not appearing. I can, and do, use the console command (/ar toggle) which allows me to continue to use this very useful addon. Thanks

### ISSUE THREAD

**Issue by crwow** [Alastair-Scott/AltReps#11]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Alastair-Scott** [comment]
Good evening Crwow! Thanks for the feeback!

I' actually notice this one myself, but wanted to finish a pretty big redesign I had been working on and have just pushed that out. Hopefully the information shoul now be easier to view, and more importantly, the button should be showing again!

Thanks for your report, time an kin words!

Please let me know if the latest upate fixes the problem for you and I will then close this off.

Thanks!
