### ISSUE TITLE
Config Changes Don't Reflect/Require Change in Number of Expansions

### ISSUE THREAD

**Issue by Ophilla** [Alastair-Scott/AltReps#14]
## Expected Behavior
Changing the number of expansions, which expansions, and which factions to display reflects immediately and persists through reloads, logs in and out, and possibly between characters.

## Current Behavior
Initially, changing the number of expansions causes no expansions to show at all. Changing the number a second time reflects the correct number of expansions, which persists after logs, character switches, etc. 

Enabling or disabling individual expansions USUALLY persists. I was showing only 5 Legion factions when I turned off all other addons for testing, after which all Legion, Shadowlands, and Dragonflight factions returned and I received an error. After this point, I turned off Dragonflight, Shadowlands, and several Legion factions again, but this caused no reputations to show and the correct results did not reflect until I modified the number of expansions to show.

## First Error
Message: Interface/AddOns/AltReps/Core.lua:2399: attempt to concatenate field 'MaxRenown' (a nil value)
Time: Mon Jan 30 15:21:33 2023
Count: 10
Stack: Interface/AddOns/AltReps/Core.lua:2399: attempt to concatenate field 'MaxRenown' (a nil value)
[string "@Interface/AddOns/AltReps/Core.lua"]:2399: in function `ShowToonFactionTooltip'
[string "@Interface/AddOns/AltReps/Core.lua"]:1641: in function <Interface/AddOns/AltReps/Core.lua:1639>

Locals: parent = StatusBar {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 Texture = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 Value = FontString {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
arg = <table> {
 factionId = 2511
 toonId = "Aephyl - Stormrage"
}
factionId = 2511
toonId = "Aephyl - Stormrage"
toon = <table> {
 Show = true
 SortOrder = 25
 Reps = <table> {
 }
 LFaction = "Alliance"
 Faction = "Alliance"
 Class = "PALADIN"
 LClass = "Paladin"
 Server = "Stormrage"
}
faction = <table> {
 Show = true
 For = "Alliance;Horde"
 Name = "Iskaara Tuskarr"
 ExpansionId = 10
}
rep = <table> {
 Max = 6000
 Current = 0
 RenownLevel = 0
 Standing = 5
}
standingLine = 2
(*temporary) = <function> defined @Interface/AddOns/AltReps/Libs/LibQTip-1.0/LibQTip-1.0.lua:1295
(*temporary) = Frame {
 0 = <userdata>
 regularFont = GameTooltipText {
 }
 OnRelease = <function> defined @Interface/AddOns/AltReps/Core.lua:2550
 layoutType = "TooltipDefaultLayout"
 headerFont = GameTooltipHeaderText {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:191
 key = "AltRepsIndicatorTooltip"
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:195
 scrollFrame = ScrollFrame {
 }
 autoHideTimerFrame = Frame {
 }
 columns = <table> {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:203
 scrollChild = Frame {
 }
 colspans = <table> {
 }
 TooltipBackdropOnLoad = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:172
 width = 112.506180
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:199
 labelProvider = <table> {
 }
 height = 31.074077
 SetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:187
 lines = <table> {
 }
 NineSlice = Frame {
 }
}
(*temporary) = 2
(*temporary) = 2
(*temporary) = 0
(*temporary) = " / "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = Frame {
 0 = <userdata>
 regularFont = GameTooltipText {
 }
 OnRelease = <function> defined @Interface/AddOns/AltReps/Core.lua:2550
 layoutType = "TooltipDefaultLayout"
 headerFont = GameTooltipHeaderText {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:191
 key = "AltRepsIndicatorTooltip"
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/SharedTooltipTemplates.lua:195
 scrollFrame = ScrollFrame {
 }
 autoHideTimerFrame = Frame {
 }

## Second Error
This is the version of the error that was given after I re-enabled BugGrabber/BugSack.

51x AltReps/Core.lua:2399: attempt to concatenate field 'MaxRenown' (a nil value)
[string "@AltReps/Core.lua"]:2399: in function `ShowToonFactionTooltip'
[string "@AltReps/Core.lua"]:1641: in function <AltReps/Core.lua:1639>

Locals:
parent = StatusBar {
 0 = <userdata>
 PixelSnapDisabled = true
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 Texture = Texture {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 backdrop = Frame {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 Value = FontString {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
}
arg = <table> {
 factionId = 2510
 toonId = "Awanaj - Area 52"
}
factionId = 2510
toonId = "Awanaj - Area 52"
toon = <table> {
 Class = "MONK"
 Show = true
 SortOrder = 5
 Reps = <table> {
 }
 Faction = "Horde"
 LFaction = "Horde"
 LClass = "Monk"
 Server = "Area 52"
}
faction = <table> {
 Show = true
 For = "Alliance;Horde"
 Name = "Valdrakken Accord"
 ExpansionId = 10
}
rep = <table> {
 Current = 0
 Max = 6000
 RenownLevel = 0
 Standing = 5
}
standingLine = 2
(*temporary) = <function> defined @AltReps/Libs/LibQTip-1.0/LibQTip-1.0.lua:1295
(*temporary) = Frame {
 SetBorderBlendMode = <function> defined @SharedXML/SharedTooltipTemplates.lua:203
 OnLeave = <function> defined @gmGuildFriends/core.lua:161
 OnRelease = <function> defined @AltReps/Core.lua:2550
 layoutType = "TooltipDefaultLayout"
 headerFont = GameTooltipHeaderText {
 }
 GetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:191
 key = "AltRepsIndicatorTooltip"
 SetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:195
 regularFont = GameTooltipText {
 }
 scrollFrame = ScrollFrame {
 }
 backdrop = Frame {
 }
 autoHideTimerFrame = Frame {
 }
 columns = <table> {
 }
 0 = <userdata>
 scrollChild = Frame {
 }
 colspans = <table> {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:172
 width = 155.325928
 GetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:199
 labelProvider = <table> {
 }
 lines = <table> {
 }
 height = 44.822224
 SetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:187
 NineSlice = Frame {
 }
 slider = Slider {
 }
}
(*temporary) = 2
(*temporary) = 2
(*temporary) = 0
(*temporary) = " / "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = Frame {
 SetBorderBlendMode = <function> defined @SharedXML/SharedTooltipTemplates.lua:203
 OnLeave = <function> defined @gmGuildFriends/core.lua:161
 OnRelease = <function> defined @AltReps/Core.lua:2550
 layoutType = "TooltipDefaultLayout"
 headerFont = GameTooltipHeaderText {
 }
 GetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:191
 key = "AltRepsIndicatorTooltip"
 SetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:195
 regularFont = GameTooltipText {
 }
 scrollFrame = ScrollFrame {
 }
 backdrop = Frame {
 }
 autoHideTimerFrame = Frame {
 }
 columns = <table> {
 }
 0 = <userdata>
 scrollChild = Frame {
 }
 colspans = <table> {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:172
 width = 155.325928
 GetBackd

**Comment by Alfakennyone** [comment]
yea, still broken...

settings don't save when changing what factions/expansion you want to see

**Comment by Alastair-Scott** [comment]
Hey Alfakennyone,

I'm very sorry about the delay with this. Strangly, the issue you were experiencing above looks to be the same as an issue I noticed with tooltips with characters that are currently on 0 renown. I have just pushed out a fix (along with adding the new reps and another fix) that should be live soon.

Please let me know if this works for you, and again, I'm sorry for the delay!

**Comment by Alfakennyone** [comment]
hello, no worries about the delay.


All fine and dandy now! thank you


________________________________

**Comment by Alastair-Scott** [comment]
Amazing! Thanks for raising :)
