### ISSUE TITLE
New install of Version: v1.2.0 - errors on world entry

### ISSUE THREAD

**Issue by scottishbearviking** [Alastair-Scott/AltReps#6]
Errors received upon entering the game.  No minimap icon, though /AR TOGGLE brings up the GUI.

## Expected Behavior

No errors.

## Current Behavior

Errors received from Bug Grabber both listed as local errors at 211:

1x ...AltReps\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:3: LibDataBroker-1.1 requires CallbackHandler-1.0
[string "=[C]"]: in function `assert'
[string "@AltReps\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua"]:3: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "LibDataBroker-1.1 requires CallbackHandler-1.0"

1x AltReps\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:12: LibDBIcon-1.0 requires LibDataBroker-1.1.
[string "=[C]"]: in function `error'
[string "@AltReps\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:12: in main chunk

Locals:
(*temporary) = "LibDBIcon-1.0 requires LibDataBroker-1.1."

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Alastair-Scott** [comment]
Hi @scottishbearviking, I'm sorry for the delay in noticing this!

I have an idea of what's causing this, and will investigate this evening.

Do you have any other addons loaded? I think I missed this issue because I've been testing it with a couple of other addons enabled and they may cover the issue.

**Comment by scottishbearviking** [comment]
I use several addons, such as NDUI, DBM, Skada, etc, but with all addons
disabled I still receive this error.

**Comment by Alastair-Scott** [comment]
I've pushed out a code update that I think should fix this issue.

Could you please let me know if the latest version (v1.2.1) fixes the issue?

Thanks!

**Comment by scottishbearviking** [comment]
That did the job.  Thanks a bunch.  Stay safe!

**Comment by Alastair-Scott** [comment]
Brilliant, thanks for letting me know!

Same to you!
