### ISSUE TITLE
Improved cross-realm support

### ISSUE THREAD

**Issue by Sildris** [Alastair-Scott/AltReps#7]
Thanks for the great addon! It's much needed and holding up well. 

## Feature / Idea
Auto-hiding of characters on other realms

## What's the feature for / What does it solve?
Currently, all characters are shown if selected, regardless of realm. 

Could you please add the ability to auto-filter characters from other realms?

It would be very handy if you retained the ability to see all characters, if needed, such as by pressing the alt-key. 

Much appreciated, 
Sildris

**Comment by Alastair-Scott** [comment]
Glad you like it @Sildris! It's been a fun challenge to work on.

I can add a setting to hide / show characters on different servers easily enough; not sure about how I'd implement the alt-key logic though. 

As an alternative, I could offer an option where it shows all characters, but grouped by server, with the current characters server showing first.

Thinking of an option like:
Show characters on all servers:
- Only the server I'm on
- Show all characters
- Show all characters, grouped by server

What are your thoughts?

**Comment by Sildris** [comment]
I agree the code can quickly get out of hand with complex functionality with show/hide on key press. 

I think your suggestion would work well. 
Most of the time I need to check characters on the current server, but occasionally need to compare progress on other servers. Having the flexibility to hide or group characters on other servers with quick option toggle would be a great help. 

Thanks again!

**Comment by Alastair-Scott** [comment]
Hi @Sildris, I hope everything's going ok?

I've finally found some time to look into this again and have got a version up and running where you can choose to group or filter your characters by server/connected realm. I'm going to close this ticket for now, but feel free to give me a shout if you spot anything that needs tweaking!

Thanks!
