### ISSUE TITLE
Support for Pre-legion factions

### ISSUE THREAD

**Issue by Sildris** [Alastair-Scott/AltReps#8]
## What's the feature for / What does it solve?

Can you please add support for pre-legion factions? (If you weren't planning to already).
These could be off by default as you already have the ability to choose which to display.  

Great addon so far!
Much appreciated, 
Sildris

**Comment by Alastair-Scott** [comment]
Hi @Sildris ,

I know it's been a little while, but I've now got more reputations showing in my addon (Disabled by default as per your suggestion which I liked a lot!)

Please let me know if there's anything I missed!

Thanks!
